### ISSUE TITLE
[v1.4.0] report() in a blade view causes an infinite loop

### ISSUE THREAD

**Issue by fabio-ivona** [spatie/flare-client-php#16]
It seems that calling `report('....')` inside a blade view file, causes flare-client-php to render again the view in: 

https://github.com/spatie/flare-client-php/blob/f8d80bca1eb72b1157f7d244663d4493f4d1d7d0/src/Report.php#L318

this leads to this:

https://github.com/spatie/backtrace/blob/85d484be410674d68620bde530e5cb692f1260ff/src/Arguments/Reducers/StringableArgumentReducer.php#L19

that leads the View.php to trigger its ->toString() method and enter an infinite loop as it executes  `report('...')` again

to reproduce the issue, just render this simple blade file:

//test.blade.php
```blade
@php
    report('failure');
@endphp
```

**Comment by freekmurze** [comment]
We'll investigate this soon. If someone already knows a good fix, do send a PR 👍

**Comment by ganyicz** [comment]
Adding my two cents: https://github.com/spatie/laravel-flare/issues/2

Sorry for the duplicate, I only discovered this issue after making the one above.

Probably not that serious if it's been here for that long, will send a PR this week.
